# Problem 1

In [3]:
#@title Linear Kernel with C=0.001
from sklearn import svm
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

df = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Data')
df = df.to_numpy()
X = df[:,:]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
y = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Binary response')
y = y.to_numpy()
y = y.ravel()

clf = svm.SVC(kernel='linear', C=0.001, random_state=0, max_iter=10e8)
acc = cross_val_score(clf, X, y, cv=10)
f1 = cross_val_score(clf, X, y, scoring='f1_macro', cv=10)
print("accuracy : ",acc)
print("f1_measure is : ",f1)

accuracy is :  [0.69230769 0.61538462 0.76923077 0.69230769 0.69230769 0.69230769
 0.75       1.         0.83333333 0.91666667]
f1_measure is :  [0.33333333 0.         0.4        0.         0.         0.
 0.4        1.         0.66666667 0.85714286]


In [32]:
#@title Linear Kernel with C=1
from sklearn import svm
import pandas as pd
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import StandardScaler

df = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Data')
df = df.to_numpy()
X = df[:,:]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
y = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Binary response')
y = y.to_numpy()
y = y.ravel()
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score

clf = svm.SVC(kernel='linear', C=1.0, random_state=0, max_iter=10e8)
acc = cross_val_score(clf, X, y, cv=10)
f1 = cross_val_score(clf, X, y, scoring='f1_macro', cv=10)
print("accuracy : ",acc)
print("f1_measure is : ",f1)

accuracy :  [0.92307692 0.92307692 0.76923077 0.76923077 0.76923077 0.61538462
 1.         0.83333333 0.75       0.66666667]
f1_measure is :  [0.92121212 0.92121212 0.74509804 0.62857143 0.74509804 0.5112782
 1.         0.82857143 0.73333333 0.65714286]


In [31]:
#@title Linear Kernel with C=1
from sklearn import svm
import pandas as pd
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import StandardScaler

df = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Data')
df = df.to_numpy()
X = df[:,:]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
y = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Binary response')
y = y.to_numpy()
y = y.ravel()
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score

clf = svm.SVC(kernel='linear', C=20.0, random_state=0, max_iter=10e8)
acc = cross_val_score(clf, X, y, cv=10)
f1 = cross_val_score(clf, X, y, scoring='f1_macro', cv=10)
print("accuracy : ",acc)
print("f1_measure is : ",f1)

accuracy :  [0.92307692 0.92307692 0.76923077 0.76923077 0.76923077 0.61538462
 1.         0.83333333 0.75       0.66666667]
f1_measure is :  [0.92121212 0.92121212 0.74509804 0.62857143 0.74509804 0.5112782
 1.         0.82857143 0.73333333 0.65714286]


In the previous section, we selected different values for the parameter C, and according to the result, it can be seen that the parameter C is more appropriate with a value of 20, and in other words, it performs the regularization better.

In [34]:
#@title Polynomial Kernel With C=20 and degree=2
from sklearn import svm
import pandas as pd
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score

df = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Data')
df = df.to_numpy()
X = df[:,:]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
y = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Binary response')
y = y.to_numpy()
y = y.ravel()

clf = svm.SVC(kernel='poly', C=20, random_state=0, max_iter=10e8, degree=2)
acc = cross_val_score(clf, X, y, cv=10)
f1 = cross_val_score(clf, X, y, scoring='f1_macro', cv=10)
print("accuracy : ",acc)
print(acc.mean())
print("f1_measure is : ",f1)
print(f1.mean())

accuracy :  [0.76923077 0.61538462 0.84615385 0.61538462 0.53846154 0.46153846
 0.75       1.         0.91666667 0.83333333]
0.7346153846153847
f1_measure is :  [0.74509804 0.61538462 0.81944444 0.5112782  0.35       0.31578947
 0.69747899 1.         0.91111111 0.82857143]
0.6794156299496856


In [36]:
#@title Polynomial Kernel With C=20 and degree=3
from sklearn import svm
import pandas as pd
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

df = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Data')
df = df.to_numpy()
X = df[:,:]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
y = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Binary response')
y = y.to_numpy()
y = y.ravel()

clf = svm.SVC(kernel='poly', C=20, random_state=0, max_iter=10e8, degree=3)
acc = cross_val_score(clf, X, y, cv=10)
f1 = cross_val_score(clf, X, y, scoring='f1_macro', cv=10)
print("accuracy : ",acc)
print(acc.mean())
print("f1_measure is : ",f1)
print(f1.mean())

accuracy :  [0.76923077 0.76923077 0.76923077 0.69230769 0.69230769 0.76923077
 0.75       0.91666667 0.91666667 1.        ]
0.8044871794871795
f1_measure is :  [0.70676692 0.70676692 0.62857143 0.40909091 0.56666667 0.62857143
 0.62105263 0.89915966 0.89915966 1.        ]
0.7065806226796939


In [39]:
#@title Polynomial Kernel With C=20 and degree=5
from sklearn import svm
import pandas as pd
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score

df = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Data')
df = df.to_numpy()
X = df[:,:]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
y = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Binary response')
y = y.to_numpy()
y = y.ravel()

clf = svm.SVC(kernel='poly', C=20, random_state=0, max_iter=10e8, degree=5)
acc = cross_val_score(clf, X, y, cv=10)
f1 = cross_val_score(clf, X, y, scoring='f1_macro', cv=10)
print("accuracy : ",acc)
print(acc.mean())
print("f1_measure is : ",f1)
print(f1.mean())

accuracy :  [0.69230769 0.61538462 0.69230769 0.69230769 0.61538462 0.76923077
 0.75       0.75       0.75       0.75      ]
0.7076923076923076
f1_measure is :  [0.56666667 0.38095238 0.40909091 0.40909091 0.38095238 0.62857143
 0.62105263 0.62105263 0.62105263 0.62105263]
0.5259535201640464


In the previous section, we selected different values for the degree of the model, and according to the result, it can be seen that the model with a degree of 3 has a higher accuracy.

in this part we choose different gamma for rbf kernel.
if gamma='scale' (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,

if ‘auto’, uses 1 / n_features.


In [43]:
#@title RBF Kernel With C=20 and gamma = scale
from sklearn import svm
import pandas as pd
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score

df = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Data')
df = df.to_numpy()
X = df[:,:]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
y = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Binary response')
y = y.to_numpy()
y = y.ravel()

clf = svm.SVC(kernel='rbf', C=20, random_state=0, max_iter=10e8)
acc = cross_val_score(clf, X, y, cv=10)
f1 = cross_val_score(clf, X, y, scoring='f1_macro', cv=10)
print("accuracy : ",acc)
print(acc.mean())
print("f1_measure is : ",f1)
print(f1.mean())

accuracy :  [0.92307692 0.92307692 0.76923077 0.84615385 0.69230769 0.76923077
 1.         0.83333333 0.91666667 0.75      ]
0.8423076923076923
f1_measure is :  [0.92121212 0.92121212 0.74509804 0.78333333 0.63888889 0.62857143
 1.         0.82857143 0.91111111 0.73333333]
0.8111331805449451


In [66]:
#@title RBF Kernel With C=20 and gamma = auto
from sklearn import svm
import pandas as pd
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score

df = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Data')
df = df.to_numpy()
X = df[:,:]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
y = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Binary response')
y = y.to_numpy()
y = y.ravel()

clf = svm.SVC(kernel='rbf', C=20, random_state=0, max_iter=10e8, gamma='auto')
acc = cross_val_score(clf, X, y, cv=10)
f1 = cross_val_score(clf, X, y, scoring='f1_macro', cv=10)
print("accuracy : ",acc)
print(acc.mean())
print("f1_measure is : ",f1)
print(f1.mean())

accuracy :  [0.92307692 0.92307692 0.76923077 0.84615385 0.69230769 0.76923077
 1.         0.83333333 0.91666667 0.75      ]
0.8423076923076923
f1_measure is :  [0.92121212 0.92121212 0.74509804 0.78333333 0.63888889 0.62857143
 1.         0.82857143 0.91111111 0.73333333]
0.8111331805449451


In [72]:
#@title RBF Kernel With C=15 and gamma = scale
from sklearn import svm
import pandas as pd
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score

df = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Data')
df = df.to_numpy()
X = df[:,:]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
y = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Binary response')
y = y.to_numpy()
y = y.ravel()

clf = svm.SVC(kernel='rbf', C=15, random_state=0, max_iter=10e8)
acc = cross_val_score(clf, X, y, cv=10)
f1 = cross_val_score(clf, X, y, scoring='f1_macro', cv=10)
print("accuracy : ",acc)
print(acc.mean())
print("f1_measure is : ",f1)
print(f1.mean())

accuracy :  [0.92307692 0.92307692 0.76923077 0.84615385 0.69230769 0.76923077
 1.         0.83333333 0.91666667 0.75      ]
0.8423076923076923
f1_measure is :  [0.92121212 0.92121212 0.74509804 0.78333333 0.63888889 0.62857143
 1.         0.82857143 0.91111111 0.73333333]
0.8111331805449451


In [53]:
#@title sigmoid Kernel With C=20
from sklearn import svm
import pandas as pd
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score

df = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Data')
df = df.to_numpy()
X = df[:,:]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
y = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Binary response')
y = y.to_numpy()
y = y.ravel()

clf = svm.SVC(kernel='sigmoid', C=20, random_state=0, max_iter=10e8)
acc = cross_val_score(clf, X, y, cv=10)
f1 = cross_val_score(clf, X, y, scoring='f1_macro', cv=10)
print("accuracy : ",acc)
print(acc.mean())
print("f1_measure is : ",f1)
print(f1.mean())

accuracy :  [1.         0.76923077 0.69230769 0.84615385 0.84615385 0.61538462
 1.         0.75       0.66666667 0.83333333]
0.801923076923077
f1_measure is :  [1.         0.76923077 0.63888889 0.78333333 0.78333333 0.5112782
 1.         0.73333333 0.66666667 0.8125    ]
0.7698564520275046


# Best Model

In [56]:
#@title sigmoid Kernel With C=10
from sklearn import svm
import pandas as pd
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score

df = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Data')
df = df.to_numpy()
X = df[:,:]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
y = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Binary response')
y = y.to_numpy()
y = y.ravel()

clf = svm.SVC(kernel='sigmoid', C=10, random_state=0, max_iter=10e8)
acc = cross_val_score(clf, X, y, cv=15)
f1 = cross_val_score(clf, X, y, scoring='f1_macro', cv=10)
print("accuracy : ",acc)
print(acc.mean())
print("f1_measure is : ",f1)
print(f1.mean())

accuracy :  [1.         1.         0.88888889 0.88888889 0.77777778 0.88888889
 0.875      0.75       0.75       1.         1.         0.75
 0.875      0.875      0.875     ]
0.8796296296296297
f1_measure is :  [1.         0.92121212 0.81944444 0.78333333 0.78333333 0.56666667
 1.         0.82857143 0.66666667 0.8125    ]
0.8181727994227994


In [73]:
#@title sigmoid Kernel With C=15
from sklearn import svm
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score

df = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Data')
df = df.to_numpy()
X = df[:,:]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
y = pd.read_excel('LSVT_voice_rehabilitation.xlsx', sheet_name='Binary response')
y = y.to_numpy()
y = y.ravel()

clf = svm.SVC(kernel='sigmoid', C=15, random_state=0, max_iter=10e8)
acc = cross_val_score(clf, X, y, cv=10)
f1 = cross_val_score(clf, X, y, scoring='f1_macro', cv=10)
print("accuracy : ",acc)
print(acc.mean())
print("f1_measure is : ",f1)
print(f1.mean())

accuracy :  [1.         0.92307692 0.76923077 0.84615385 0.84615385 0.69230769
 1.         0.75       0.66666667 0.83333333]
0.8326923076923076
f1_measure is :  [1.         0.92121212 0.74509804 0.78333333 0.78333333 0.56666667
 1.         0.73333333 0.66666667 0.8125    ]
0.801214349376114


In the previous section, we selected different values for C parametr for model, and according to the result, it can be seen that the model with value of C= 10 and sigmoid kernel has a highest accuracy in all models.

# Problem 2

In [ ]:

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

df = pd.read_csv('data_train.csv')
X_train = df.iloc[:,:16]
y_train = df.iloc[:,16:]
print('Shape of train samples :', X_train.shape)
print('Shape of train labels :', y_train.shape)
df = pd.read_csv('data_test.csv')
X_test = df.iloc[:,:16]
y_test = df.iloc[:,16:]
print('Shape of test samples :', X_test.shape)
print('Shape of test labels :', y_test.shape)
sel = RandomForestClassifier(n_estimators = 15, max_depth=3)
clf = MultiOutputClassifier(sel, n_jobs=-1)
clf.fit(X_train, y_train)
y_pred_test = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred_test)
cnfMatrix = confusion_matrix(y_test, y_pred_test)
print('accuracy of this classifier is: ', acc)
print('confusion Matrix of this classifier is: \n', cnfMatrix)

Shape of train samples : (7493, 16)
Shape of train labels : (7493, 1)
Shape of test samples : (3497, 16)
Shape of test labels : (3497, 1)
accuracy of this classifier is:  0.764941378324278
confusion Matrix of this classifier is: 
 [[323   3   0   0   0   0  23   3  11   0]
 [  0 215 111  33   3   0   2   0   0   0]
 [  0  12 334   6   1   0   4   7   0   0]
 [  0   6   0 325   1   0   0   4   0   0]
 [  0   1   3   1 358   0   0   0   0   1]
 [  0   1   0 105  34 162   7   0   6  20]
 [  2   0   6   3   0   0 319   6   0   0]
 [  0  15   9  15   3   1   0 297   0  24]
 [ 53   0   0   0   0  31  10  20 221   0]
 [  0 104   0  65  36   0   9   0   1 121]]


In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

df = pd.read_csv('data_train.csv')
X_train = df.iloc[:,:16]
y_train = df.iloc[:,16:]
print('Shape of train samples :', X_train.shape)
print('Shape of train labels :', y_train.shape)
df = pd.read_csv('data_test.csv')
X_test = df.iloc[:,:16]
y_test = df.iloc[:,16:]
print('Shape of test samples :', X_test.shape)
print('Shape of test labels :', y_test.shape)

clf = AdaBoostClassifier(DecisionTreeClassifier(max_depth=7),
    n_estimators=10)
clf.fit(X_train, y_train)
y_pred_test = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred_test)
cnfMatrix = confusion_matrix(y_test, y_pred_test)
print('accuracy of this classifier is: ', acc)
print('confusion Matrix of this classifier is: \n', cnfMatrix)

Shape of train samples : (7493, 16)
Shape of train labels : (7493, 1)
Shape of test samples : (3497, 16)
Shape of test labels : (3497, 1)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


accuracy of this classifier is:  0.9450957963969117
confusion Matrix of this classifier is: 
 [[344   0   0   0   0   0   0   0  19   0]
 [  0 317  43   3   1   0   0   0   0   0]
 [  0  14 348   0   0   0   0   2   0   0]
 [  0   2   0 330   0   2   0   1   0   1]
 [  0   3   0   1 354   0   1   0   0   5]
 [  0   6   0  16   0 297   0   0   1  15]
 [  0   1   0   0   0   0 334   0   1   0]
 [  0  17   2   1   0   0   0 331   1  12]
 [  1   0   0   0   0   2   0   1 331   0]
 [  0   8   0   8   0   0   0   0   1 319]]


In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

df = pd.read_csv('data_train.csv')
X_train = df.iloc[:,:16]
y_train = df.iloc[:,16:]
print('Shape of train samples :', X_train.shape)
print('Shape of train labels :', y_train.shape)
df = pd.read_csv('data_test.csv')
X_test = df.iloc[:,:16]
y_test = df.iloc[:,16:]
print('Shape of test samples :', X_test.shape)
print('Shape of test labels :', y_test.shape)

clf = AdaBoostClassifier(DecisionTreeClassifier(max_depth=7),
    n_estimators=5)
clf.fit(X_train, y_train)
y_pred_test = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred_test)
cnfMatrix = confusion_matrix(y_test, y_pred_test)
print('accuracy of this classifier is: ', acc)
print('confusion Matrix of this classifier is: \n', cnfMatrix)

Shape of train samples : (7493, 16)
Shape of train labels : (7493, 1)
Shape of test samples : (3497, 16)
Shape of test labels : (3497, 1)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


accuracy of this classifier is:  0.9279382327709466
confusion Matrix of this classifier is: 
 [[345   0   0   0   1   0   0   0  16   1]
 [  0 321  40   2   1   0   0   0   0   0]
 [  0  18 342   0   0   0   0   4   0   0]
 [  0   3   0 330   0   2   0   0   0   1]
 [  0   2   1   1 353   0   3   1   0   3]
 [  0  10   0  14   0 281   0   0   5  25]
 [  0   0   1   0   0   6 327   0   2   0]
 [  0  21   4   6  15   0   0 311   5   2]
 [  2   1   0   0   0   5   0   1 326   0]
 [  0  10   0  10   3   0   0   1   3 309]]


In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

df = pd.read_csv('data_train.csv')
X_train = df.iloc[:,:16]
y_train = df.iloc[:,16:]
print('Shape of train samples :', X_train.shape)
print('Shape of train labels :', y_train.shape)
df = pd.read_csv('data_test.csv')
X_test = df.iloc[:,:16]
y_test = df.iloc[:,16:]
print('Shape of test samples :', X_test.shape)
print('Shape of test labels :', y_test.shape)

clf = AdaBoostClassifier(DecisionTreeClassifier(max_depth=7),
    n_estimators=20)
clf.fit(X_train, y_train)
y_pred_test = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred_test)
cnfMatrix = confusion_matrix(y_test, y_pred_test)
print('accuracy of this classifier is: ', acc)
print('confusion Matrix of this classifier is: \n', cnfMatrix)

Shape of train samples : (7493, 16)
Shape of train labels : (7493, 1)
Shape of test samples : (3497, 16)
Shape of test labels : (3497, 1)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


accuracy of this classifier is:  0.9613954818415785
confusion Matrix of this classifier is: 
 [[347   0   0   0   0   0   0   0  16   0]
 [  0 334  28   0   1   0   0   1   0   0]
 [  0   8 354   0   0   0   0   2   0   0]
 [  0   1   0 333   0   0   0   1   0   1]
 [  0   1   0   0 358   3   0   0   0   2]
 [  0   0   0   8   0 315   0   0   5   7]
 [  0   2   0   0   0   0 334   0   0   0]
 [  0  25   4   3   0   0   0 322   3   7]
 [  0   0   0   0   0   0   0   0 335   0]
 [  0   2   0   1   0   0   0   2   1 330]]


In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

df = pd.read_csv('data_train.csv')
X_train = df.iloc[:,:16]
y_train = df.iloc[:,16:]
print('Shape of train samples :', X_train.shape)
print('Shape of train labels :', y_train.shape)
df = pd.read_csv('data_test.csv')
X_test = df.iloc[:,:16]
y_test = df.iloc[:,16:]
print('Shape of test samples :', X_test.shape)
print('Shape of test labels :', y_test.shape)

clf = AdaBoostClassifier(DecisionTreeClassifier(max_depth=7),
    n_estimators=50)
clf.fit(X_train, y_train)
y_pred_test = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred_test)
cnfMatrix = confusion_matrix(y_test, y_pred_test)
print('accuracy of this classifier is: ', acc)
print('confusion Matrix of this classifier is: \n', cnfMatrix)

Shape of train samples : (7493, 16)
Shape of train labels : (7493, 1)
Shape of test samples : (3497, 16)
Shape of test labels : (3497, 1)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


accuracy of this classifier is:  0.9659708321418359
confusion Matrix of this classifier is: 
 [[344   0   0   0   0   0   0   0  19   0]
 [  0 340  21   2   1   0   0   0   0   0]
 [  0   5 359   0   0   0   0   0   0   0]
 [  0   1   0 334   0   0   0   0   0   1]
 [  0   0   0   0 360   2   1   0   0   1]
 [  0   1   0   7   0 313   0   0   0  14]
 [  0   0   0   0   0   1 335   0   0   0]
 [  0  28   2   0   0   0   0 330   1   3]
 [  0   0   0   0   0   1   0   0 334   0]
 [  0   3   0   1   0   0   0   2   1 329]]


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix

df = pd.read_csv('data_train.csv')
df.columns = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q']
X_train = df.iloc[:,:16]
y_train = df.iloc[:,16:]
print('Shape of train samples :', X_train.shape)
print('Shape of train labels :', y_train.shape)
df = pd.read_csv('data_test.csv')
df.columns = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q']
X_test = df.iloc[:,:16]
y_test = df.iloc[:,16:]
print('Shape of test samples :', X_test.shape)
print('Shape of test labels :', y_test.shape)

dtrain = xgb.DMatrix(data=X_train, label=y_train)
dtest = xgb.DMatrix(data=X_test)


params = {
    'max_depth': 6,
    'objective': 'multi:softmax',  # error evaluation for multiclass training
    'num_class': 10
}
bst = xgb.train(params, dtrain)
pred = bst.predict(dtest)

print(classification_report(y_test, pred))
cm = confusion_matrix(y_test, pred)
print(cm)

Shape of train samples : (7493, 16)
Shape of train labels : (7493, 1)
Shape of test samples : (3497, 16)
Shape of test labels : (3497, 1)
              precision    recall  f1-score   support

           0       0.99      0.94      0.97       363
           1       0.87      0.87      0.87       364
           2       0.88      0.96      0.92       364
           3       0.95      0.98      0.96       336
           4       0.96      0.98      0.97       364
           5       0.98      0.90      0.94       335
           6       0.99      0.99      0.99       336
           7       0.98      0.89      0.94       364
           8       0.93      0.99      0.96       335
           9       0.92      0.94      0.93       336

    accuracy                           0.94      3497
   macro avg       0.95      0.95      0.95      3497
weighted avg       0.95      0.94      0.94      3497

[[343   0   0   0   0   0   0   0  20   0]
 [  0 318  44   0   0   0   0   2   0   0]
 [  0  12 351   0